version: '3'
services:
  db:
    image: ghcr.io/hpinc/krypton/krypton-db
    hostname: ${DB}.${DOMAIN}
    container_name: ${DB}.${DOMAIN}
    ports:
    - ${DB_PORT}:${DB_PORT}
    networks:
      backend:
        aliases:
        - ${DB}.${DOMAIN}
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    tty: true
  cache:
    image: ghcr.io/hpinc/krypton/krypton-cache
    hostname: ${CACHE}.${DOMAIN}
    container_name: ${CACHE}.${DOMAIN}
    ports:
    - ${CACHE_PORT}:${CACHE_PORT}
    networks:
      backend:
        aliases:
        - ${CACHE}.${DOMAIN}
    environment:
    - CACHE_PASSWORD=${CACHE_PASSWORD}
    tty: true
  jwt:
    image: ghcr.io/hpinc/krypton/krypton-jwtserver
    hostname: ${JWT}.${DOMAIN}
    container_name: ${JWT}.${DOMAIN}
    environment:
    - JWT_TOKEN_VALID_MINUTES=${JWT_TOKEN_VALID_MINUTES}
    ports:
    - ${JWT_PORT}:${JWT_PORT}
    networks:
      backend:
        aliases:
        - ${JWT}.${DOMAIN}
    volumes:
    - ./jwtprivateKey.pem:/go/bin/privateKey.pem:ro
    tty: true
networks:
  backend:
    driver: bridge
