name: CI for Krypton Enrollment Service
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build the ES docker image
      run: make -C es docker

    - name: Build the ES worker docker image
      run: make -C es-worker docker

    - name: Run the ES unit tests
      run: make -C es test

    - name: Run the ES worker unit tests
      run: make -C es-worker test

    - name: Cleanup
      if: always()
      run: make -C es clean && make -C es-worker clean && docker logout
